In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])

In [3]:
arr1

array([1, 2, 3, 4])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.ndim

1

In [6]:
arr1.shape

(4,)

In [7]:
len(arr1)

4

In [9]:
arr1[1]

2

In [10]:
arr1[-1]

4

In [11]:
arr1[0:2]

array([1, 2])

# Lists

In [12]:
list1 = [1,2,3]
list2 = [4,5,6]

In [13]:
list1+list2

[1, 2, 3, 4, 5, 6]

In [24]:
list3 = [1,2,3,4,'shankar', 4+7j]

In [25]:
list3

[1, 2, 3, 4, 'shankar', (4+7j)]

# Numpy arrays

In [14]:
arr1

array([1, 2, 3, 4])

In [15]:
arr2 = np.array([5,6,7,8])

In [16]:
arr2

array([5, 6, 7, 8])

In [17]:
arr1+arr2

array([ 6,  8, 10, 12])

In [18]:
arr1

array([1, 2, 3, 4])

In [19]:
arr2

array([5, 6, 7, 8])

In [20]:
arr3 = np.array([1,2,3, 'shankar'])

In [21]:
arr3

array(['1', '2', '3', 'shankar'], dtype='<U11')

In [22]:
arr3[0]

'1'

In [23]:
type(arr3[0])

numpy.str_

In [ ]:
arr1.