In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])

In [3]:
arr1

array([1, 2, 3])

In [4]:
arr1.ndim

1

In [5]:
arr1.shape

(3,)

In [6]:
arr1[0]

1

In [7]:
arr1[1]

2

In [8]:
arr1[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

# Two dimensional numpy array

In [9]:
arr2 = np.array([
                    [1,2,3],
                    [4,5,6]
                ]
               )

In [10]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 3)

In [13]:
arr2[0,0]

1

In [14]:
arr2[0,1]

2

In [15]:
arr2[0,:]

array([1, 2, 3])

In [16]:
arr2[0]

array([1, 2, 3])

In [17]:
arr2[1]

array([4, 5, 6])

In [18]:
arr2[1,:]

array([4, 5, 6])

In [19]:
arr2[1,1]

5

In [20]:
arr2[:,0]

array([1, 4])

# Three dimensional arrays

In [21]:
arr3 = np.array([
                    [
                        [1,2,3]
                    ]
                ]
               )

In [22]:
arr3.ndim

3

In [23]:
arr3.shape

(1, 1, 3)

# Four dimensional array

In [24]:
arr4 = np.array([
                    [
                        [
                            [1,2,3]
                        ]
                    ]
                ]
               )

In [25]:
arr4.ndim

4

In [26]:
arr4.shape

(1, 1, 1, 3)

In [27]:
arr4 = np.array([
                    [
                        [
                            [1,2,3],
                            [4,5,6]
                        ]
                    ]
                ]
               )

In [28]:
arr4

array([[[[1, 2, 3],
         [4, 5, 6]]]])

In [29]:
arr4.shape

(1, 1, 2, 3)

In [30]:
arr4 = np.array([
                    [
                        [
                            [1,2,3],
                            [4,5,6]
                        ],
                        [
                            [11,22,33],
                            [44,55,66]
                        ]
                    ]
                ]
               )

In [31]:
arr4

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[11, 22, 33],
         [44, 55, 66]]]])

In [32]:
arr4.ndim

4

In [33]:
arr4.shape

(1, 2, 2, 3)

In [34]:
arr4[0]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [35]:
arr4[0,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr4[0,0,0]

array([1, 2, 3])

In [37]:
arr4[0,1]

array([[11, 22, 33],
       [44, 55, 66]])

In [38]:
arr4[0,1,1]

array([44, 55, 66])

In [39]:
arr4[0,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr4[0,0][:,0]

array([1, 4])

In [41]:
arr4[0,0,:,0]

array([1, 4])