max(), min(), argmax(), argmin()

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])

In [3]:
arr2 = np.array([
                    [1,2,3,4],
                    [5,6,7,8]
                ]
               )

In [4]:
arr1.max()

4

In [5]:
arr2.max()

8

In [6]:
arr2.max(axis=0)

array([5, 6, 7, 8])

In [7]:
arr2.max(axis=1)

array([4, 8])

In [8]:
arr2.min()

1

In [9]:
arr2.min(axis=0)

array([1, 2, 3, 4])

In [10]:
arr2.min(axis=1)

array([1, 5])

In [13]:
arr1

array([1, 2, 3, 4])

In [11]:
arr1.argmax()

3

In [12]:
arr1.max()

4

In [14]:
arr1.argmin()

0

In [15]:
arr1.min()

1

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.min()

1

In [17]:
arr2.argmin()

0

In [19]:
arr2.max()

8

In [20]:
arr2.argmax()

7

In [21]:
arr2.argmin(axis=0)

array([0, 0, 0, 0], dtype=int64)

In [22]:
arr2.argmax(axis=0)

array([1, 1, 1, 1], dtype=int64)

In [23]:
arr2.argmin(axis = 1)

array([0, 0], dtype=int64)

In [24]:
arr2.argmax(axis = 1)

array([3, 3], dtype=int64)