# Logical And
Truth table:

Input_1  Input_2  Result(logical And)

    1      1        1
    
    1      0        0
    
    0      1        0
    
    0      0        0
    
# Logical Or

Truth table:

Input_1  Input_2  Result(logical Or)

    1      1        1
    
    1      0        1
    
    0      1        1
    
    0      0        0

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,-1])

In [3]:
arr1

array([ 1,  2,  3, -1])

In [4]:
arr1.all()

True

In [5]:
arr2 = np.array([[1,2,3],
                 [0,2,4]])

In [6]:
arr2

array([[1, 2, 3],
       [0, 2, 4]])

In [7]:
arr2.shape

(2, 3)

In [8]:
arr2.ndim

2

In [9]:
arr2.all()

False

In [10]:
arr2.all(axis=0)

array([False,  True,  True])

In [11]:
arr2.all(axis=1)

array([ True, False])

In [12]:
arr2.all(keepdims = True)

array([[False]])

In [13]:
arr2.all(axis = 0, keepdims = True)

array([[False,  True,  True]])

In [14]:
arr2.all(axis = 1, keepdims = True)

array([[ True],
       [False]])

In [15]:
arr2.all(axis = 1, keepdims = True).shape

(2, 1)

In [16]:
arr2

array([[1, 2, 3],
       [0, 2, 4]])

In [17]:
arr2.any()

True

In [18]:
arr2.any(axis = 0)

array([ True,  True,  True])

In [19]:
arr2.any(axis = 0, keepdims = True)

array([[ True,  True,  True]])

In [20]:
arr2.any(axis=1)

array([ True,  True])

In [21]:
arr2.any(axis=1, keepdims = True)

array([[ True],
       [ True]])

In [22]:
arr1

array([ 1,  2,  3, -1])

In [23]:
arr2

array([[1, 2, 3],
       [0, 2, 4]])

In [24]:
arr1

array([ 1,  2,  3, -1])

In [25]:
arr3 = np.array([3,4,5,6])

In [26]:
arr3

array([3, 4, 5, 6])

In [27]:
arr1>arr3

array([False, False, False, False])

In [28]:
np.all(arr1>arr3)

False

In [30]:
arr1

array([ 1,  2,  3, -1])

In [29]:
np.all(arr1<5)

True

In [31]:
arr1<5

array([ True,  True,  True,  True])

In [32]:
arr1

array([ 1,  2,  3, -1])

In [33]:
arr3

array([3, 4, 5, 6])

In [34]:
np.any(arr1>arr3)

False

In [35]:
np.any(arr1>2)

True

In [36]:
arr1>2

array([False, False,  True, False])