In [1]:
import numpy as np

In [2]:
arr2 = np.array([
                    [1,2,3,4],
                    [2,3,4,5],
                    [3,4,5,6],
                    [4,5,6,7]
                ]
               )

In [3]:
arr2.shape

(4, 4)

In [4]:
arr2.ndim

2

In [5]:
rav = arr2.ravel()

In [6]:
rav

array([1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6, 4, 5, 6, 7])

In [7]:
rav.ndim

1

In [8]:
rav[0]

1

In [9]:
rav[0] = 111

In [10]:
rav

array([111,   2,   3,   4,   2,   3,   4,   5,   3,   4,   5,   6,   4,
         5,   6,   7])

In [11]:
arr2

array([[111,   2,   3,   4],
       [  2,   3,   4,   5],
       [  3,   4,   5,   6],
       [  4,   5,   6,   7]])

In [12]:
arr2

array([[111,   2,   3,   4],
       [  2,   3,   4,   5],
       [  3,   4,   5,   6],
       [  4,   5,   6,   7]])

In [13]:
flat = arr2.flatten()

In [14]:
flat

array([111,   2,   3,   4,   2,   3,   4,   5,   3,   4,   5,   6,   4,
         5,   6,   7])

In [15]:
flat[0]

111

In [16]:
flat[0] = 1

In [17]:
flat

array([1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6, 4, 5, 6, 7])

In [18]:
arr2

array([[111,   2,   3,   4],
       [  2,   3,   4,   5],
       [  3,   4,   5,   6],
       [  4,   5,   6,   7]])