In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [3]:
arr1.shape

(3, 3)

In [4]:
arr1.ndim

2

In [5]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Reshape

In [6]:
arr1.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
result = arr1.reshape(9,1)

In [9]:
result

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [10]:
result.shape

(9, 1)

In [7]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1.ndim

In [11]:
arr1.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
arr1.reshape(9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr1.reshape(9).ndim

1

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr1.reshape(1,1,9)

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [16]:
arr1.reshape(9,1,1)

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]],

       [[9]]])

In [17]:
arr2 = np.array([
                    [1,2,3,4],
                    [5,6,7,8],
                    [9, 10, 11, 12]
                ]
               )

In [18]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arr2.shape

(3, 4)

In [20]:
arr2.ndim

2

In [21]:
arr2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
arr2.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [23]:
arr2.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [24]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr2.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [26]:
arr2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
arr2.reshape(1,6,2)

In [ ]:
arr2.reshape(1,2,6)

In [ ]:
arr2.reshape(1,2,-1)

In [ ]:
arr2

In [ ]:
arr2.squeeze()

In [ ]:
arr3 = arr2.reshape(3,4,1)

In [ ]:
arr3

# Squeeze

In [27]:
arr4 = np.array([
                    [
                        [
                            [1,2,3]
                        ],
                        [
                            [4,5,6]
                        ]
                        
                    ]
                ]
               )

In [28]:
arr4

array([[[[1, 2, 3]],

        [[4, 5, 6]]]])

In [29]:
arr4.shape

(1, 2, 1, 3)

In [30]:
arr4.ndim

4

In [31]:
arr4.squeeze()

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr4

array([[[[1, 2, 3]],

        [[4, 5, 6]]]])

In [33]:
arr4.ndim

4

In [34]:
result2 = arr4.squeeze()

In [35]:
result2

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
result2.shape

(2, 3)

In [37]:
result2.ndim

2

In [38]:
result2

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
result2.squeeze()

array([[1, 2, 3],
       [4, 5, 6]])